apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: qa
data:
  NODE_ENV: "qa"
  PORT: "3000"

  # Backend service inside cluster
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "appdb"

  # Frontend URL inside cluster
  FRONTEND_URL: "http://frontend"