apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

data:
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjM=
  DB_USER: cm9vdA==
---
apiVersion: v1
kind: Secret

metadata:
  name: mysecret

type: Opaque

data:
  MYSQL_DATABASE: bXlhcHBkYg==
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMjM=