name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  ACR_NAME: ${{ vars.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: |
          {
            "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

    # =========================
    # IMAGE TAGS (IMPORTANT)
    # =========================
    - name: Define Image Tags
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        echo "RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    # =========================
    # BUILD BACKEND
    # =========================
    - name: Build Backend Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/backend:${RUN_NUMBER} \
          -t $ACR_LOGIN_SERVER/backend:latest \
          -t $ACR_LOGIN_SERVER/backend:${SHORT_SHA} \
          -f server/Dockerfile \
          ./server

    # =========================
    # BUILD FRONTEND
    # =========================
    - name: Build Frontend Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/frontend:${RUN_NUMBER} \
          -t $ACR_LOGIN_SERVER/frontend:latest \
          -t $ACR_LOGIN_SERVER/frontend:${SHORT_SHA} \
          -f client/Dockerfile \
          ./client

    # =========================
    # PUSH BACKEND
    # =========================
    - name: Push Backend Image
      run: |
        docker push $ACR_LOGIN_SERVER/backend:${RUN_NUMBER}
        docker push $ACR_LOGIN_SERVER/backend:latest
        docker push $ACR_LOGIN_SERVER/backend:${SHORT_SHA}

    # =========================
    # PUSH FRONTEND
    # =========================
    - name: Push Frontend Image
      run: |
        docker push $ACR_LOGIN_SERVER/frontend:${RUN_NUMBER}
        docker push $ACR_LOGIN_SERVER/frontend:latest
        docker push $ACR_LOGIN_SERVER/frontend:${SHORT_SHA}

    # =========================
    # AKS ACCESS
    # =========================
    - name: Set AKS Context
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER_NAME \
          --overwrite-existing

    - name: Verify Cluster
      run: |
        kubectl get nodes